export const START_FETCHING_KELURAHAN =
  "redux/kelurahan/START_FETCHING_KELURAHAN";
export const SUCCESS_FETCHING_KELURAHAN =
  "redux/kelurahan/SUCCESS_FETCHING_KELURAHAN";
export const ERROR_FETCHING_KELURAHAN =
  "redux/kelurahan/ERROR_FETCHING_KELURAHAN";
export const CLEAR_FETCHING_KELURAHAN =
  "redux/kelurahan/CLEAR_FETCHING_KELURAHAN";
