export const START_FETCHING_KABUPATEN =
  "redux/kabupaten/START_FETCHING_KABUPATEN";
export const SUCCESS_FETCHING_KABUPATEN =
  "redux/kabupaten/SUCCESS_FETCHING_KABUPATEN";
export const ERROR_FETCHING_KABUPATEN =
  "redux/kabupaten/ERROR_FETCHING_KABUPATEN";
export const CLEAR_FETCHING_KABUPATEN =
  "redux/kabupaten/CLEAR_FETCHING_KABUPATEN";
